import { CachedLesson, ContentTopic } from '../types/index.ts';


export interface SeedLessonPack {
  topic: ContentTopic;
  lessons: CachedLesson[];
}

export const CLIENT_SEED_PACKS: SeedLessonPack[] = [
  // 1. Physics - Force, Motion & Friction
  {
    topic: {
      id: 'topic-physics-force',
      subject: 'STEM - Physics',
      grade: 7,
      topic_name: 'Force, Motion & Friction',
      topic_name_odia: 'ବଳ, ଗତି ଏବଂ ଘର୍ଷଣ',
      order_index: 1,
      lesson_count: 2,
    },
    lessons: [
      {
        id: 'lesson-force-push-pull',
        topicId: 'topic-physics-force',
        grade: 7,
        subject: 'STEM - Physics',
        title: 'Understanding Force: Push and Pull',
        titleOdia: 'ବଳର ଧାରଣା: ଠେଲା ଏବଂ ଟଣା',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Force is a push or pull upon an object resulting from its interaction with another object.',
          summaryOdia: 'ବଳ ହେଉଛି କୌଣସି ବସ୍ତୁ ଉପରେ ପ୍ରୟୋଗ କରାଯାଉଥିବା ଠେଲା ବା ଟଣା, ଯାହା ବସ୍ତୁର ଗତି ବା ଆକୃତି ବଦଳାଇପାରେ।',
          sections: [
            {
              title: 'What is Force?',
              titleOdia: 'ବଳ କ’ଣ?',
              content: 'A force is an interaction that causes an object with mass to change its velocity (moving from rest, accelerating, or changing direction). Force is measured in Newtons (N).',
              contentOdia: 'ବଳ ହେଉଛି ଏକ ବାହ୍ୟ କାରକ ଯାହା ଏକ ସ୍ଥିର ବସ୍ତୁକୁ ଗତିଶୀଳ କରିପାରେ କିମ୍ବା ଗତିଶୀଳ ବସ୍ତୁର ବେଗ ବା ଦିଗ ପରିବର୍ତ୍ତନ କରିପାରେ। ବଳର ଏକକ ହେଉଛି ନ୍ୟୁଟନ୍ (N)।',
              keyPoints: ['Forces have both magnitude and direction', 'Measured in Newtons (N)', 'Can change speed, direction, or shape of an object'],
              keyPointsOdia: ['ବଳର ପରିମାଣ ଏବଂ ଦିଗ ଉଭୟ ଥାଏ', 'ଏହାର ଏକକ ନ୍ୟୁଟନ୍ (N)', 'ଏହା ବସ୍ତୁର ଗତି, ଦିଗ ବା ଆକୃତି ବଦଳାଇପାରେ'],
            },
            {
              title: 'Types of Forces: Contact vs Non-Contact',
              titleOdia: 'ବଳର ପ୍ରକାର: ସଂସ୍ପର୍ଶ ଏବଂ ଅସଂସ୍ପର୍ଶ ବଳ',
              content: 'Contact forces require physical touch (e.g., muscular force, friction). Non-contact forces act from a distance (e.g., gravitational pull of the Earth, magnetic force).',
              contentOdia: 'ଯେଉଁ ବଳ ପ୍ରୟୋଗ ପାଇଁ ସ୍ପର୍ଶ ଦରକାର ତାହା ସଂସ୍ପର୍ଶ ବଳ (ଯଥା: ମାଂସପେଶୀୟ ବଳ, ଘର୍ଷଣ)। ଦୂରରୁ କାର୍ଯ୍ୟ କରୁଥିବା ବଳ ହେଉଛି ଅସଂସ୍ପର୍ଶ ବଳ (ଯଥା: ମାଧ୍ୟାକର୍ଷଣ, ଚୁମ୍ବକୀୟ ବଳ)।',
              keyPoints: ['Muscular force & friction are contact forces', 'Gravity and magnetism are non-contact forces'],
              keyPointsOdia: ['ମାଂସପେଶୀ ବଳ ଓ ଘର୍ଷଣ ହେଉଛି ସଂସ୍ପର୍ଶ ବଳ', 'ମାଧ୍ୟାକର୍ଷଣ ଓ ଚୁମ୍ବକୀୟ ବଳ ହେଉଛି ଅସଂସ୍ପର୍ଶ ବଳ'],
            },
          ],
          realWorldOdisha: {
            title: 'Odisha in Action: Pulling the Chariots of Puri',
            titleOdia: 'ଓଡ଼ିଶା ପ୍ରସଙ୍ଗ: ପୁରୀ ରଥଯାତ୍ରାରେ ରଥ ଟାଣିବା',
            context: 'During Puri Ratha Yatra, lakhs of devotees apply muscular tensile force to pull Nandighosha and the other sacred chariots over the Grand Road (Bada Danda). Friction between wooden wheels and the road stabilizes the motion.',
            contextOdia: 'ପୁରୀ ରଥଯାତ୍ରାରେ ବଡ଼ଦାଣ୍ଡରେ ଲକ୍ଷ ଲକ୍ଷ ଭକ୍ତ ମାଂସପେଶୀୟ ଟାଣିବା ବଳ ପ୍ରୟୋଗ କରି ନନ୍ଦିଘୋଷ ରଥ ଟାଣନ୍ତି। ଚକ ଏବଂ ରାସ୍ତା ମଧ୍ୟରେ ଥିବା ଘର୍ଷଣ ବଳ ଗତି ନିୟନ୍ତ୍ରଣରେ ସାହାଯ୍ୟ କରେ।',
          },
          funFact: {
            en: 'Without friction between your shoes and the ground, walking forward would be completely impossible!',
            or: 'ଆମ ଜୋତା ଓ ଭୂମି ମଧ୍ୟରେ ଘର୍ଷଣ ବଳ ନ ଥିଲେ ଆମେ ଆଗକୁ ଚାଲିବା ସମ୍ପୂର୍ଣ୍ଣ ଅସମ୍ଭବ ହୋଇପଡ଼ନ୍ତା!',
          },
        },
        mediaRefs: ['/media/force_puri_chariot.png'],
        questions: [
          {
            id: 'q-force-1',
            lessonId: 'lesson-force-push-pull',
            questionText: 'What is the SI unit of force?',
            questionTextOdia: 'ବଳର SI ଏକକ କ’ଣ?',
            options: ['Joule', 'Newton', 'Pascal', 'Watt'],
            optionsOdia: ['ଜୁଲ୍', 'ନ୍ୟୁଟନ୍', 'ପାସ୍କାଲ୍', 'ୱାଟ୍'],
            correctOption: 1,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-force-2',
            lessonId: 'lesson-force-push-pull',
            questionText: 'Which of the following is a non-contact force?',
            questionTextOdia: 'ନିମ୍ନଲିଖିତ ମଧ୍ୟରୁ କେଉଁଟି ଏକ ଅସଂସ୍ପର୍ଶ ବଳ?',
            options: ['Friction', 'Muscular force', 'Gravitational force', 'Tension force'],
            optionsOdia: ['ଘର୍ଷଣ ବଳ', 'ମାଂସପେଶୀୟ ବଳ', 'ମାଧ୍ୟାକର୍ଷଣ ବଳ', 'ଟାଣିବା ବଳ'],
            correctOption: 2,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-force-3',
            lessonId: 'lesson-force-push-pull',
            questionText: 'When two equal forces act on an object in opposite directions, the net force is:',
            questionTextOdia: 'ଯେତେବେଳେ ଏକ ବସ୍ତୁ ଉପରେ ଦୁଇଟି ସମାନ ବଳ ବିପରୀତ ଦିଗରେ ପ୍ରୟୋଗ ହୁଏ, ସେତେବେଳେ ମୋଟ ବଳ କେତେ ହୁଏ?',
            options: ['Doubled', 'Zero', 'Infinite', 'Negative'],
            optionsOdia: ['ଦୁଇଗୁଣ', 'ଶୂନ୍ୟ', 'ଅସୀମ', 'ଋଣାତ୍ମକ'],
            correctOption: 1,
            difficultyTag: 'medium',
            points: 15,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
      {
        id: 'lesson-friction-friend-foe',
        topicId: 'topic-physics-force',
        grade: 7,
        subject: 'STEM - Physics',
        title: 'Friction: Friend and Foe',
        titleOdia: 'ଘର୍ଷଣ: ବନ୍ଧୁ ନା ଶତ୍ରୁ?',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Friction is the resistive force that opposes relative motion between two surfaces in contact.',
          summaryOdia: 'ପରସ୍ପର ସଂସ୍ପର୍ଶରେ ଥିବା ଦୁଇଟି ତଳ ମଧ୍ୟରେ ଆପେକ୍ଷିକ ଗତିକୁ ପ୍ରତିରୋଧ କରୁଥିବା ବଳକୁ ଘର୍ଷଣ କୁହାଯାଏ।',
          sections: [
            {
              title: 'Causes of Friction',
              titleOdia: 'ଘର୍ଷଣର କାରଣ',
              content: 'Friction is caused by microscopic irregularities on contacting surfaces interlocking with each other.',
              contentOdia: 'ଦୁଇଟି ତଳର ଅଣୁବୀକ୍ଷଣୀୟ ଅସମାନତା ବା ଖାଲଖମା ପରସ୍ପର ମଧ୍ୟରେ ଛନ୍ଦି ହୋଇଯିବା ଯୋଗୁଁ ଘର୍ଷଣ ସୃଷ୍ଟି ହୁଏ।',
              keyPoints: ['Rough surfaces have higher friction', 'Smooth surfaces reduce friction', 'Lubrication creates a separating film'],
              keyPointsOdia: ['ଖସଡ଼ା ନଥିବା ଖଦଡ଼ିଆ ତଳରେ ଅଧିକ ଘର୍ଷଣ ଥାଏ', 'ତେଲ ବା ତେଲିଆ ପଦାର୍ଥ ଘର୍ଷଣ କମାଇଦିଏ'],
            },
          ],
          realWorldOdisha: {
            title: 'Odisha Fishermen at Chilika Lake',
            titleOdia: 'ଚିଲିକା ହ୍ରଦରେ ମତ୍ସ୍ୟଜୀବୀଙ୍କ ଡଙ୍ଗା',
            context: 'Fishermen at Chilika streamline the shape of their wooden boats to minimize water drag (fluid friction) so they glide smoothly.',
            contextOdia: 'ଚିଲିକା ହ୍ରଦର ଡଙ୍ଗାଚାଳକମାନେ ଡଙ୍ଗାର ଆଗ ଭାଗକୁ ଧାରାବାହୀ (ଷ୍ଟ୍ରିମଲାଇନ୍) ଆକୃତି ଦିଅନ୍ତି ଯାହାଦ୍ୱାରା ଜଳର ଘର୍ଷଣ କମିଯାଏ।',
          },
          funFact: {
            en: 'Ball bearings inside bicycle wheels replace sliding friction with rolling friction, making pedaling 90% easier!',
            or: 'ସାଇକେଲ୍ ଚକରେ ଥିବା ବଲ୍-ବେୟାରିଂ ସ୍ଲାଇଡିଂ ଘର୍ଷଣକୁ ଗଡ଼ନ୍ତା ଘର୍ଷଣରେ ବଦଳାଇ ଦିଏ!',
          },
        },
        mediaRefs: ['/media/friction_boat.png'],
        questions: [
          {
            id: 'q-fric-1',
            lessonId: 'lesson-friction-friend-foe',
            questionText: 'Which type of friction is the smallest in magnitude?',
            questionTextOdia: 'ନିମ୍ନଲିଖିତ ମଧ୍ୟରୁ କେଉଁ ଘର୍ଷଣ ସବୁଠାରୁ କମ୍?',
            options: ['Static friction', 'Sliding friction', 'Rolling friction', 'Fluid drag'],
            optionsOdia: ['ସ୍ଥିତିକ ଘର୍ଷଣ', 'ସର୍ପଣ ଘର୍ଷଣ', 'ଆବର୍ତ୍ତନ (ଗଡ଼ନ୍ତା) ଘର୍ଷଣ', 'ତରଳ ଘର୍ଷଣ'],
            correctOption: 2,
            difficultyTag: 'medium',
            points: 15,
          },
          {
            id: 'q-fric-2',
            lessonId: 'lesson-friction-friend-foe',
            questionText: 'What do lubricants do to friction between machine parts?',
            questionTextOdia: 'ଯନ୍ତ୍ରାଂଶ ମଧ୍ୟରେ ଲୁବ୍ରିକାଣ୍ଟ (ତେଲ) ପ୍ରୟୋଗ କଲେ ଘର୍ଷଣ କ’ଣ ହୁଏ?',
            options: ['Increases it', 'Reduces it', 'Eliminates gravity', 'Freezes motion'],
            optionsOdia: ['ବଢ଼ିଯାଏ', 'କମିଯାଏ', 'ଗୁରୁତ୍ୱାକର୍ଷଣ ନଷ୍ଟ ହୁଏ', 'ଗତି ବନ୍ଦ ହୁଏ'],
            correctOption: 1,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-fric-3',
            lessonId: 'lesson-friction-friend-foe',
            questionText: 'Why do athletes use spiked shoes on running tracks?',
            questionTextOdia: 'ଧାବକମାନେ କାହିଁକି କଣ୍ଟା ଥିବା ଜୋତା (ସ୍ପାଇକ୍ସ) ପିନ୍ଧନ୍ତି?',
            options: ['To reduce shoe weight', 'To increase friction and prevent slipping', 'To absorb sweat', 'To look stylish'],
            optionsOdia: ['ଜୋତାର ଓଜନ କମାଇବା ପାଇଁ', 'ଘର୍ଷଣ ବୃଦ୍ଧି କରି ଖସିପଡ଼ିବାକୁ ରୋକିବା ପାଇଁ', 'ଝାଳ ଶୋଷିବା ପାଇଁ', 'ସୁନ୍ଦର ଦେଖାଯିବା ପାଇଁ'],
            correctOption: 1,
            difficultyTag: 'medium',
            points: 15,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
    ],
  },

  // 2. Physics - Light, Reflection & Mirrors
  {
    topic: {
      id: 'topic-physics-light',
      subject: 'STEM - Physics',
      grade: 7,
      topic_name: 'Light, Shadows & Optical Reflection',
      topic_name_odia: 'ଆଲୋକ, ଛାଇ ଏବଂ ପ୍ରତିଫଳନ',
      order_index: 2,
      lesson_count: 2,
    },
    lessons: [
      {
        id: 'lesson-light-reflection-mirrors',
        topicId: 'topic-physics-light',
        grade: 7,
        subject: 'STEM - Physics',
        title: 'Reflection of Light and Plane Mirrors',
        titleOdia: 'ଆଲୋକର ପ୍ରତିଫଳନ ଏବଂ ସମତଳ ଦର୍ପଣ',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Light travels in straight lines and bounces off shiny surfaces following the laws of reflection.',
          summaryOdia: 'ଆଲୋକ ସର୍ବଦା ସରଳ ରେଖାରେ ଗତି କରେ ଏବଂ ଚିକ୍କଣ ପୃଷ୍ଠରେ ପଡ଼ି ପ୍ରତିଫଳିତ ହୁଏ।',
          sections: [
            {
              title: 'Laws of Reflection',
              titleOdia: 'ପ୍ରତିଫଳନର ନିୟମାବଳୀ',
              content: '1. Incident ray, reflected ray, and normal lie in the same plane.\n2. Angle of incidence equals angle of reflection (∠i = ∠r).',
              contentOdia: '୧. ଆପତିତ ରଶ୍ମି, ପ୍ରତିଫଳିତ ରଶ୍ମି ଏବଂ ଆପତନ ବିନ୍ଦୁରେ ଅଙ୍କିତ ଅଭିଲମ୍ବ ଏକ ସମତଳରେ ରହନ୍ତି।\n୨. ଆପତନ କୋଣ = ପ୍ରତିଫଳନ କୋଣ।',
              keyPoints: ['Angle of incidence = Angle of reflection', 'Images in plane mirrors are virtual and laterally inverted'],
              keyPointsOdia: ['ଆପତନ କୋଣ = ପ୍ରତିଫଳନ କୋଣ', 'ସମତଳ ଦର୍ପଣରେ ପ୍ରତିବିମ୍ବ ଆଭାସୀ, ସଳଖ ଏବଂ ପାର୍ଶ୍ୱ ପରିବର୍ତ୍ତିତ ହୁଏ'],
            },
          ],
          realWorldOdisha: {
            title: 'Konark Sun Temple & Astronomical Alignment',
            titleOdia: 'କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର ଏବଂ ସୂର୍ଯ୍ୟକିରଣର ଜ୍ୟାମିତି',
            context: 'The 13th-century Konark Sun Temple was engineered so that dawn rays struck the sanctum sanctorum through precise optical alignment.',
            contextOdia: 'କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର ଏପରି ଭାବରେ ନିର୍ମିତ ହୋଇଥିଲା ଯେ ପ୍ରଭାତର ପ୍ରଥମ ସୂର୍ଯ୍ୟକିରଣ ସିଧାସଳଖ ଗର୍ଭଗୃହର ପ୍ରତିମା ଉପରେ ପଡୁଥିଲା।',
          },
          funFact: {
            en: 'In a plane mirror, your right hand appears as your left hand. This is called lateral inversion!',
            or: 'ଆଇନାରେ ତୁମର ଡାହାଣ ହାତ ବାମ ହାତ ଭଳି ଦେଖାଯାଏ, ଏହାକୁ ପାର୍ଶ୍ୱୀୟ ବିପରୀତତା କୁହାଯାଏ!',
          },
        },
        mediaRefs: ['/media/light_konark.png'],
        questions: [
          {
            id: 'q-light-1',
            lessonId: 'lesson-light-reflection-mirrors',
            questionText: 'If a ray of light strikes a mirror at an angle of incidence of 35°, what is the angle of reflection?',
            questionTextOdia: 'ଯଦି ଆଲୋକ ରଶ୍ମି ୩୫° ଆପତନ କୋଣରେ ଏକ ଦର୍ପଣ ଉପରେ ପଡ଼େ, ତେବେ ପ୍ରତିଫଳନ କୋଣ କେତେ ହେବ?',
            options: ['0°', '35°', '70°', '90°'],
            optionsOdia: ['୦°', '୩୫°', '୭୦°', '୯୦°'],
            correctOption: 1,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-light-2',
            lessonId: 'lesson-light-reflection-mirrors',
            questionText: 'Which mirror is commonly used as a rear-view mirror in vehicles?',
            questionTextOdia: 'ଗାଡ଼ିର ପଛପଟ ଦେଖିବା ପାଇଁ (ରିଅର୍-ଭ୍ୟୁ ମିରର୍) କେଉଁ ଦର୍ପଣ ବ୍ୟବହୃତ ହୁଏ?',
            options: ['Concave mirror', 'Convex mirror', 'Plane mirror', 'Cylindrical mirror'],
            optionsOdia: ['ଅବତଳ ଦର୍ପଣ', 'ଉତ୍ତଳ ଦର୍ପଣ', 'ସମତଳ ଦର୍ପଣ', 'ବେଳଣାକାର ଦର୍ପଣ'],
            correctOption: 1,
            difficultyTag: 'medium',
            points: 15,
          },
          {
            id: 'q-light-3',
            lessonId: 'lesson-light-reflection-mirrors',
            questionText: 'The splitting of white light into its seven component colors is known as:',
            questionTextOdia: 'ଧଳା ଆଲୋକ ସାତୋଟି ରଙ୍ଗରେ ବିଭାଜିତ ହେବା ପ୍ରକ୍ରିୟାକୁ କ’ଣ କୁହାଯାଏ?',
            options: ['Diffraction', 'Dispersion', 'Absorption', 'Total Internal Reflection'],
            optionsOdia: ['ବିବର୍ତ୍ତନ', 'ବିଚ୍ଛୁରଣ (Dispersion)', 'ଅବଶୋଷଣ', 'ପୂର୍ଣ୍ଣ ଆଭ୍ୟନ୍ତରୀଣ ପ୍ରତିଫଳନ'],
            correctOption: 1,
            difficultyTag: 'hard',
            points: 20,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
      {
        id: 'lesson-spherical-mirrors',
        topicId: 'topic-physics-light',
        grade: 7,
        subject: 'STEM - Physics',
        title: 'Spherical Mirrors: Concave and Convex',
        titleOdia: 'ଗୋଲକୀୟ ଦର୍ପଣ: ଅବତଳ ଏବଂ ଉତ୍ତଳ',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Spherical mirrors have curved reflecting surfaces that can converge or diverge light rays.',
          summaryOdia: 'ଗୋଲକୀୟ ଦର୍ପଣର ପ୍ରତିଫଳକ ପୃଷ୍ଠ ବକ୍ର ହୋଇଥାଏ, ଯାହା ଆଲୋକକୁ କେନ୍ଦ୍ରୀଭୂତ ବା ବିକେନ୍ଦ୍ରୀଭୂତ କରିପାରେ।',
          sections: [
            {
              title: 'Concave vs Convex Mirrors',
              titleOdia: 'ଅବତଳ ବନାମ ଉତ୍ତଳ ଦର୍ପଣ',
              content: 'A concave mirror curves inward and focuses light. A convex mirror curves outward and gives a wide field of view.',
              contentOdia: 'ଅବତଳ ଦର୍ପଣ ଆଲୋକକୁ କେନ୍ଦ୍ରୀଭୂତ କରେ। ଉତ୍ତଳ ଦର୍ପଣ ବିସ୍ତୃତ ଅଞ୍ଚଳ ଦେଖାଇବାରେ ସାହାଯ୍ୟ କରେ।',
              keyPoints: ['Concave mirrors can form real and inverted or virtual magnified images', 'Convex mirrors always form diminished, erect, virtual images'],
              keyPointsOdia: ['ଅବତଳ ଦର୍ପଣ ବାସ୍ତବ ଓ ବଡ଼ ପ୍ରତିବିମ୍ବ ଗଠନ କରିପାରେ', 'ଉତ୍ତଳ ଦର୍ପଣ ସର୍ବଦା ଛୋଟ, ସଳଖ ଓ ଆଭାସୀ ପ୍ରତିବିମ୍ବ ଗଠନ କରେ'],
            },
          ],
          realWorldOdisha: {
            title: 'Solar Cookers in Rural Odisha',
            titleOdia: 'ଓଡ଼ିଶାର ଗ୍ରାମାଞ୍ଚଳରେ ସୌର ଚୁଲା',
            context: 'In rural districts like Mayurbhanj, concave reflectors concentrate sunlight for solar cooking.',
            contextOdia: 'ମୟୂରଭଞ୍ଜ ପରି ଜିଲ୍ଲାରେ ଅବତଳ ଦର୍ପଣ ବ୍ୟବହାର କରି ସୂର୍ଯ୍ୟାଲୋକକୁ କେନ୍ଦ୍ରୀଭୂତ କରି ରନ୍ଧନ କାର୍ଯ୍ୟ କରାଯାଏ।',
          },
          funFact: {
            en: 'The inside of a metal spoon is a concave mirror, while the back is a convex mirror!',
            or: 'ଏକ ଷ୍ଟିଲ୍ ଚାମଚର ଭିତର ପାଖ ଅବତଳ ଦର୍ପଣ ଏବଂ ପଛ ପାଖ ଉତ୍ତଳ ଦର୍ପଣ ଭଳି କାମ କରେ!',
          },
        },
        mediaRefs: ['/media/solar_cooker_mirror.png'],
        questions: [
          {
            id: 'q-sph-1',
            lessonId: 'lesson-spherical-mirrors',
            questionText: 'Dentists use which type of mirror to examine enlarged images of teeth?',
            questionTextOdia: 'ଦନ୍ତ ଚିକିତ୍ସକ ଦାନ୍ତର ବଡ଼ ପ୍ରତିବିମ୍ବ ଦେଖିବା ପାଇଁ କେଉଁ ଦର୍ପଣ ବ୍ୟବହାର କରନ୍ତି?',
            options: ['Convex mirror', 'Concave mirror', 'Plane mirror', 'Double convex lens'],
            optionsOdia: ['ଉତ୍ତଳ ଦର୍ପଣ', 'ଅବତଳ ଦର୍ପଣ', 'ସମତଳ ଦର୍ପଣ', 'ଉଭୟୋତ୍ତଳ ଲେନ୍ସ'],
            correctOption: 1,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-sph-2',
            lessonId: 'lesson-spherical-mirrors',
            questionText: 'What type of image is ALWAYS formed by a convex mirror?',
            questionTextOdia: 'ଉତ୍ତଳ ଦର୍ପଣ ଦ୍ୱାରା ସର୍ବଦା କେଉଁ ପ୍ରକାରର ପ୍ରତିବିମ୍ବ ସୃଷ୍ଟି ହୁଏ?',
            options: ['Real, inverted and enlarged', 'Virtual, erect and diminished', 'Real, erect and same size', 'Virtual, inverted and enlarged'],
            optionsOdia: ['ବାସ୍ତବ, ଓଲଟା ଓ ବଡ଼', 'ଆଭାସୀ, ସଳଖ ଓ ଛୋଟ', 'ବାସ୍ତବ, ସଳଖ ଓ ସମାନ ଆକାର', 'ଆଭାସୀ, ଓଲଟା ଓ ବଡ଼'],
            correctOption: 1,
            difficultyTag: 'medium',
            points: 15,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
    ],
  },

  // 3. Chemistry - Acids, Bases & Indicators
  {
    topic: {
      id: 'topic-chem-acids',
      subject: 'STEM - Chemistry',
      grade: 7,
      topic_name: 'Acids, Bases & Natural Indicators',
      topic_name_odia: 'ଅମ୍ଳ, କ୍ଷାରକ ଏବଂ ପ୍ରାକୃତିକ ସୂଚକ',
      order_index: 3,
      lesson_count: 2,
    },
    lessons: [
      {
        id: 'lesson-acids-bases-daily-life',
        topicId: 'topic-chem-acids',
        grade: 7,
        subject: 'STEM - Chemistry',
        title: 'Acids and Bases in Daily Life',
        titleOdia: 'ଦୈନନ୍ଦିନ ଜୀବନରେ ଅମ୍ଳ ଏବଂ କ୍ଷାରକ',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Acids taste sour and turn blue litmus red. Bases taste bitter, feel soapy, and turn red litmus blue.',
          summaryOdia: 'ଅମ୍ଳ ଖଟା ସ୍ୱାଦଯୁକ୍ତ ଏବଂ ନୀଳ ଲିଟମସକୁ ନାଲି କରେ। କ୍ଷାରକ ପିତା ସ୍ୱାଦଯୁକ୍ତ ଏବଂ ନାଲି ଲିଟମସକୁ ନୀଳ କରେ।',
          sections: [
            {
              title: 'Properties of Acids and Bases',
              titleOdia: 'ଅମ୍ଳ ଓ କ୍ଷାରକର ଧର୍ମ',
              content: 'Natural acids include citric acid in lemons and lactic acid in curd. Common bases include sodium hydroxide in soaps.',
              contentOdia: 'ପ୍ରାକୃତିକ ଅମ୍ଳ: ଲେମ୍ବୁରେ ସାଇଟ୍ରିକ୍ ଏସିଡ୍, ଦହିରେ ଲାକ୍ଟିକ୍ ଏସିଡ୍। କ୍ଷାରକ: ସାବୁନରେ ସୋଡ଼ିୟମ୍ ହାଇଡ୍ରକ୍ସାଇଡ୍।',
              keyPoints: ['Acids: pH < 7, sour taste, turn blue litmus red', 'Bases: pH > 7, bitter taste, soapy touch, turn red litmus blue'],
              keyPointsOdia: ['ଅମ୍ଳ: pH < ୭, ଖଟା ସ୍ୱାଦ', 'କ୍ଷାରକ: pH > ୭, ପିତା ସ୍ୱାଦ'],
            },
          ],
          realWorldOdisha: {
            title: 'Odisha Pakhala & Turmeric Indicator',
            titleOdia: 'ଓଡ଼ିଶାର ପଖାଳ ଓ ହଳଦୀ ସୂଚକ',
            context: 'Turmeric is a natural indicator. On contact with soap (base), yellow stains turn red.',
            contextOdia: 'ହଳଦୀ ଏକ ପ୍ରାକୃତିକ ସୂଚକ। ସାବୁନ (କ୍ଷାରୀୟ) ସଂସ୍ପର୍ଶରେ ଆସିଲେ ଏହା ଲାଲ୍ ହୋଇଯାଏ।',
          },
          funFact: {
            en: 'Ant stings inject formic acid. Applying baking soda paste neutralizes it immediately!',
            or: 'ପିମ୍ପୁଡ଼ି କାମୁଡ଼ିଲେ ଫର୍ମିକ୍ ଏସିଡ୍ ନିର୍ଗତ ହୁଏ। ବେକିଂ ସୋଡ଼ା ଲଗାଇଲେ ଏହା ଶାନ୍ତ ହୁଏ!',
          },
        },
        mediaRefs: ['/media/acid_base_litmus.png'],
        questions: [
          {
            id: 'q-acid-1',
            lessonId: 'lesson-acids-bases-daily-life',
            questionText: 'Which acid is present in curd/yogurt?',
            questionTextOdia: 'ଦହିରେ କେଉଁ ଏସିଡ୍ ଥାଏ?',
            options: ['Acetic acid', 'Lactic acid', 'Citric acid', 'Oxalic acid'],
            optionsOdia: ['ଏସିଟିକ୍ ଏସିଡ୍', 'ଲାକ୍ଟିକ୍ ଏସିଡ୍', 'ସାଇଟ୍ରିକ୍ ଏସିଡ୍', 'ଅକ୍ସାଲିକ୍ ଏସିଡ୍'],
            correctOption: 1,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-acid-2',
            lessonId: 'lesson-acids-bases-daily-life',
            questionText: 'What happens when a drop of soap solution is added to a turmeric paste paper strip?',
            questionTextOdia: 'ହଳଦୀ କାଗଜ ଉପରେ ସାବୁନ ପାଣି ଢାଳିଲେ ରଙ୍ଗ କିପରି ବଦଳେ?',
            options: ['Remains yellow', 'Turns blue', 'Turns reddish-brown', 'Turns green'],
            optionsOdia: ['ହଳଦିଆ ରହେ', 'ନୀଳ ହୁଏ', 'ଲାଲ୍-ବାଦାମୀ ହୁଏ', 'ସବୁଜ ହୁଏ'],
            correctOption: 2,
            difficultyTag: 'medium',
            points: 15,
          },
          {
            id: 'q-acid-3',
            lessonId: 'lesson-acids-bases-daily-life',
            questionText: 'The reaction between an acid and a base to form salt and water is called:',
            questionTextOdia: 'ଅମ୍ଳ ଏବଂ କ୍ଷାରକ ମଧ୍ୟରେ ପ୍ରତିକ୍ରିୟା ଘଟି ଲବଣ ଓ ଜଳ ସୃଷ୍ଟି ହେବାକୁ କ’ଣ କୁହାଯାଏ?',
            options: ['Neutralization', 'Oxidation', 'Fermentation', 'Distillation'],
            optionsOdia: ['ପ୍ରଶମନ (Neutralization)', 'ଜାରଣ', 'କିଣ୍ୱନ', 'ପରିସ୍ରବଣ'],
            correctOption: 0,
            difficultyTag: 'medium',
            points: 15,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
      {
        id: 'lesson-neutralization-soil',
        topicId: 'topic-chem-acids',
        grade: 7,
        subject: 'STEM - Chemistry',
        title: 'Neutralization and Soil Treatment',
        titleOdia: 'ପ୍ରଶମନ ପ୍ରକ୍ରିୟା ଏବଂ ମୃତ୍ତିକା ସଂଶୋଧନ',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Neutralization is the reaction between an acid and a base, producing salt, water, and heat.',
          summaryOdia: 'ଅମ୍ଳ ଏବଂ କ୍ଷାରକ ମିଶି ପରସ୍ପରର ପ୍ରଭାବକୁ ନଷ୍ଟ କରି ଲବଣ ଓ ଜଳ ସୃଷ୍ଟି କରନ୍ତି।',
          sections: [
            {
              title: 'Treating Acidic Agricultural Soil',
              titleOdia: 'ଅମ୍ଳୀୟ କୃଷି ମୃତ୍ତିକାର ଉପଚାର',
              content: 'Excessive fertilizer makes soil acidic. Farmers add quicklime (calcium oxide) to restore pH balance.',
              contentOdia: 'ଚାଷୀମାନେ ଅମ୍ଳୀୟ ମାଟିରେ ପୋଡ଼ାଚୂନ ପ୍ରୟୋଗ କରି ମାଟିକୁ ସନ୍ତୁଳିତ କରନ୍ତି।',
              keyPoints: ['Acid + Base → Salt + Water + Heat', 'Quicklime neutralizes acidic agricultural soil'],
              keyPointsOdia: ['ଅମ୍ଳ + କ୍ଷାରକ → ଲବଣ + ଜଳ', 'ଚୂନ ଅମ୍ଳୀୟ ମାଟିକୁ ସନ୍ତୁଳିତ କରେ'],
            },
          ],
          realWorldOdisha: {
            title: 'Odisha Coastal Saline & Acidic Soils',
            titleOdia: 'ଓଡ଼ିଶାର ଉପକୂଳବର୍ତ୍ତୀ ମାଟିର ପରୀକ୍ଷା',
            context: 'Agricultural officers in Balasore test soil pH and advise lime application for optimal rice yield.',
            contextOdia: 'ବାଲେଶ୍ୱରର କୃଷି ବିଭାଗ ମାଟିର pH ମାପି ଚୂନ ପ୍ରୟୋଗ ପାଇଁ ପରାମର୍ଶ ଦିଅନ୍ତି।',
          },
          funFact: {
            en: 'Milk of Magnesia is a mild base used as an antacid to relieve stomach heartburn!',
            or: 'ମିଲ୍କ ଅଫ୍ ମ୍ୟାଗ୍ନେସିଆ ଏକ ମୃଦୁ କ୍ଷାରକ ଯାହା ଏସିଡିଟି ଦୂର କରେ!',
          },
        },
        mediaRefs: ['/media/soil_ph_neutralization.png'],
        questions: [
          {
            id: 'q-neut-1',
            lessonId: 'lesson-neutralization-soil',
            questionText: 'What should be added to soil that has become too acidic?',
            questionTextOdia: 'ଅତ୍ୟଧିକ ଅମ୍ଳୀୟ ହୋଇଥିବା ମାଟିରେ କ’ଣ ପ୍ରୟୋଗ କରାଯାଏ?',
            options: ['Organic compost', 'Quicklime or slaked lime', 'Dilute vinegar', 'Common salt'],
            optionsOdia: ['ଜୈବିକ ଖତ', 'ପୋଡ଼ାଚୂନ ବା ଚୂନ ପାଣି', 'ଭିନେଗାର୍', 'ଖାଇବା ଲୁଣ'],
            correctOption: 1,
            difficultyTag: 'medium',
            points: 15,
          },
          {
            id: 'q-neut-2',
            lessonId: 'lesson-neutralization-soil',
            questionText: 'Which substance is used as an antacid tablet?',
            questionTextOdia: 'ଏସିଡିଟିରୁ ମୁକ୍ତି ପାଇବା ପାଇଁ ଆଣ୍ଟାସିଡ୍ ଔଷଧରେ କ’ଣ ଥାଏ?',
            options: ['Hydrochloric acid', 'Magnesium hydroxide', 'Sodium chloride', 'Sulfuric acid'],
            optionsOdia: ['ହାଇଡ୍ରୋକ୍ଲୋରିକ୍ ଏସିଡ୍', 'ମ୍ୟାଗ୍ନେସିୟମ୍ ହାଇଡ୍ରକ୍ସାଇଡ୍', 'ସୋଡ଼ିୟମ୍ କ୍ଲୋରାଇଡ୍', 'ସଲଫ୍ୟୁରିକ୍ ଏସିଡ୍'],
            correctOption: 1,
            difficultyTag: 'hard',
            points: 20,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
    ],
  },

  // 4. Biology - Plant Nutrition & Photosynthesis
  {
    topic: {
      id: 'topic-bio-photosynthesis',
      subject: 'STEM - Biology',
      grade: 7,
      topic_name: 'Plant Nutrition & Photosynthesis',
      topic_name_odia: 'ଉଦ୍ଭିଦରେ ପୋଷଣ ଏବଂ ଆଲୋକସଂଶ୍ଳେଷଣ',
      order_index: 4,
      lesson_count: 2,
    },
    lessons: [
      {
        id: 'lesson-autotrophic-nutrition',
        topicId: 'topic-bio-photosynthesis',
        grade: 7,
        subject: 'STEM - Biology',
        title: 'Autotrophic Nutrition & Chlorophyll',
        titleOdia: 'ସ୍ୱଭୋଜୀ ପୋଷଣ ଏବଂ ହରିତ୍ କଣିକା',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Green plants synthesize their own food using sunlight, water, carbon dioxide, and chlorophyll through photosynthesis.',
          summaryOdia: 'ସବୁଜ ଉଦ୍ଭିଦମାନେ ସୂର୍ଯ୍ୟାଲୋକ, ଜଳ, ଅଙ୍ଗାରକାମ୍ଳ ଏବଂ ହରିତ୍‌କଣିକା ସାହାଯ୍ୟରେ ନିଜ ଖାଦ୍ୟ ନିଜେ ପ୍ରସ୍ତୁତ କରନ୍ତି।',
          sections: [
            {
              title: 'Photosynthesis Equation',
              titleOdia: 'ଆଲୋକସଂଶ୍ଳେଷଣର ରାସାୟନିକ ସମୀକରଣ',
              content: 'Carbon dioxide + Water + Sunlight (Chlorophyll) → Glucose (Carbohydrate) + Oxygen gas.',
              contentOdia: 'ଅଙ୍ଗାରକାମ୍ଳ (CO₂) + ଜଳ (H₂O) + ସୂର୍ଯ୍ୟାଲୋକ (ହରିତକଣା) → ଶର୍କରା (ଗ୍ଲୁକୋଜ୍) + ଅମ୍ଳଜାନ (O₂)।',
              keyPoints: ['Leaves are the food factories of plants', 'Stomata allow gas exchange (CO2 in, O2 out)', 'Chlorophyll captures solar radiation'],
              keyPointsOdia: ['ପତ୍ର ହେଉଛି ଉଦ୍ଭିଦର ରୋଷେଇଶାଳା', 'ଷ୍ଟୋମାଟା (ସ୍ତୋମ) ଦ୍ୱାରା ବାୟୁ ବିନିମୟ ହୁଏ', 'କ୍ଲୋରୋଫିଲ୍ ସୌରଶକ୍ତି ଗ୍ରହଣ କରେ'],
            },
          ],
          realWorldOdisha: {
            title: 'Similipal Biosphere Reserve Canopy',
            titleOdia: 'ଶିମିଳିପାଳ ଜୈବମଣ୍ଡଳ ଓ ସାଳ ଜଙ୍ଗଲ',
            context: 'The dense Sal and Mahua forests of Similipal in Mayurbhanj act as the green oxygen lungs of Odisha.',
            contextOdia: 'ଶିମିଳିପାଳ ଅଭୟାରଣ୍ୟର ସାଳ ଓ ମହୁଲ ଗଛ ଆଲୋକସଂଶ୍ଳେଷଣ ଦ୍ୱାରା ଓଡ଼ିଶାକୁ ପ୍ରଚୁର ଅମ୍ଳଜାନ ପ୍ରଦାନ କରନ୍ତି।',
          },
          funFact: {
            en: 'Algae in oceans and wetlands produce more than 50% of the world’s entire oxygen supply through photosynthesis!',
            or: 'ପୃଥିବୀର ୫୦% ରୁ ଅଧିକ ଅମ୍ଳଜାନ ଜଳଭଣ୍ଡାରରେ ଥିବା ଶୈବାଳ (Algae) ପ୍ରସ୍ତୁତ କରନ୍ତି!',
          },
        },
        mediaRefs: ['/media/photosynthesis_diagram.png'],
        questions: [
          {
            id: 'q-photo-1',
            lessonId: 'lesson-autotrophic-nutrition',
            questionText: 'What green pigment in plant leaves traps sunlight for photosynthesis?',
            questionTextOdia: 'ସୂର୍ଯ୍ୟାଲୋକ ଶୋଷଣ କରିବା ପାଇଁ ପତ୍ରରେ କେଉଁ ସବୁଜ ରଙ୍ଗର କଣିକା ଥାଏ?',
            options: ['Hemoglobin', 'Chlorophyll', 'Melanin', 'Carotene'],
            optionsOdia: ['ହିମୋଗ୍ଲୋବିନ୍', 'ହରିତ୍‌କଣା (Chlorophyll)', 'ମେଲାନିନ୍', 'କାରୋଟିନ୍'],
            correctOption: 1,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-photo-2',
            lessonId: 'lesson-autotrophic-nutrition',
            questionText: 'The microscopic pores on leaves through which gas exchange takes place are called:',
            questionTextOdia: 'ପତ୍ରରେ ଥିବା ଯେଉଁ କ୍ଷୁଦ୍ର ରନ୍ଧ୍ର ଦ୍ୱାରା ବାୟୁ ବିନିମୟ ହୁଏ ତାହାକୁ କ’ଣ କୁହାଯାଏ?',
            options: ['Vessels', 'Stomata', 'Xylem', 'Root hairs'],
            optionsOdia: ['ନାଳୀ', 'ସ୍ତୋମ (Stomata)', 'ଜାଇଲେମ୍', 'ମୂଳଲୋମ'],
            correctOption: 1,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-photo-3',
            lessonId: 'lesson-autotrophic-nutrition',
            questionText: 'Which gas is released into the atmosphere as a byproduct of photosynthesis?',
            questionTextOdia: 'ଆଲୋକସଂଶ୍ଳେଷଣ ପ୍ରକ୍ରିୟାରେ କେଉଁ ଗ୍ୟାସ୍ ବାୟୁମଣ୍ଡଳକୁ ନିର୍ଗତ ହୁଏ?',
            options: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Methane'],
            optionsOdia: ['ଅଙ୍ଗାରକାମ୍ଳ', 'ଯବକ୍ଷାରଜାନ', 'ଅମ୍ଳଜାନ (Oxygen)', 'ମିଥେନ୍'],
            correctOption: 2,
            difficultyTag: 'medium',
            points: 15,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
      {
        id: 'lesson-heterotrophic-plants',
        topicId: 'topic-bio-photosynthesis',
        grade: 7,
        subject: 'STEM - Biology',
        title: 'Heterotrophic & Insectivorous Plants',
        titleOdia: 'ପରଭୋଜୀ ଏବଂ କୀଟଭୋଜୀ ଉଦ୍ଭିଦ',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Some non-green plants survive as parasites or saprophytes, while insectivorous plants trap insects for nitrogen.',
          summaryOdia: 'କେତେକ ଉଦ୍ଭିଦ ପରଜୀବୀ କିମ୍ବା ମୃତୋପଜୀବୀ ଭାବରେ ବଞ୍ଚନ୍ତି ଏବଂ କୀଟଭୋଜୀ ଉଦ୍ଭିଦ କୀଟପତଙ୍ଗ ଖାଆନ୍ତି।',
          sections: [
            {
              title: 'Insectivorous Adaptations',
              titleOdia: 'କୀଟଭୋଜୀ ଉଦ୍ଭିଦର ଅନୁକୂଳନ',
              content: 'Pitcher plants (Nepenthes) and Venus Flytraps grow in nitrogen-deficient soil and trap insects to absorb essential nitrates.',
              contentOdia: 'କଳସୀ ପତ୍ରୀ (Pitcher plant) ଉଦ୍ଭିଦ ଯବକ୍ଷାରଜାନ ଅଭାବ ଥିବା ମାଟିରେ ବଢ଼ନ୍ତି ଏବଂ ପୋକଜୋକ ଧରି ଖାଆନ୍ତି।',
              keyPoints: ['Cuscuta (Amarbel) is a total plant parasite', 'Pitcher plant is both photosynthetic and insectivorous'],
              keyPointsOdia: ['ନିର୍ମୂଳୀ (Amarbel) ଏକ ପରଜୀବୀ ଉଦ୍ଭିଦ', 'କଳସୀ ପତ୍ରୀ କୀଟ ଖାଇ ଯବକ୍ଷାରଜାନ ପାଏ'],
            },
          ],
          realWorldOdisha: {
            title: 'Odisha Tribal Forests & Wild Mushrooms',
            titleOdia: 'ଓଡ଼ିଶାର ଜଙ୍ଗଲରେ ଛତୁ ଓ ମୃତୋପଜୀବୀ ଉଦ୍ଭିଦ',
            context: 'In Koraput, tribal communities harvest edible wild mushrooms that grow on decaying organic matter as saprotrophs.',
            contextOdia: 'କୋରାପୁଟର ଜଙ୍ଗଲରେ ପ୍ରାକୃତିକ ଛତୁ ମୃତ ଜୈବ ପଦାର୍ଥରୁ ପୋଷଣ ଗ୍ରହଣ କରି ବଢ଼େ।',
          },
          funFact: {
            en: 'The Pitcher plant’s leaf is modified into a slippery jug with digestive enzymes to trap insects!',
            or: 'କଳସୀ ପତ୍ରୀ ଗଛର ପତ୍ର ଏକ ପିଚର ବା ପାତ୍ର ଆକାର ଧାରଣ କରି ପୋକଜୋକ ହଜମ କରେ!',
          },
        },
        mediaRefs: ['/media/pitcher_plant.png'],
        questions: [
          {
            id: 'q-het-1',
            lessonId: 'lesson-heterotrophic-plants',
            questionText: 'Which of the following is a parasitic plant that lacks chlorophyll?',
            questionTextOdia: 'ନିମ୍ନଲିଖିତ ମଧ୍ୟରୁ କେଉଁଟି ଏକ ପରଜୀବୀ ଉଦ୍ଭିଦ ଯାହାର ହରିତ୍‌କଣା ନ ଥାଏ?',
            options: ['Mango tree', 'Cuscuta (Amarbel)', 'Pitcher plant', 'Rose'],
            optionsOdia: ['ଆମ୍ବ ଗଛ', 'ନିର୍ମୂଳୀ ଲତା (Amarbel)', 'କଳସୀ ପତ୍ରୀ', 'ଗୋଲାପ'],
            correctOption: 1,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-het-2',
            lessonId: 'lesson-heterotrophic-plants',
            questionText: 'Why do insectivorous plants like Pitcher plants trap and digest insects?',
            questionTextOdia: 'କଳସୀ ପତ୍ରୀ ଗଛ କାହିଁକି କୀଟପତଙ୍ଗ ଶିକାର କରେ?',
            options: ['To obtain water', 'To obtain nitrogen/nitrates', 'To get sunlight', 'To defend territory'],
            optionsOdia: ['ଜଳ ପାଇବା ପାଇଁ', 'ଯବକ୍ଷାରଜାନ (Nitrogen) ଅଭାବ ପୂରଣ ପାଇଁ', 'ସୂର୍ଯ୍ୟାଲୋକ ପାଇଁ', 'ଆତ୍ମରକ୍ଷା ପାଇଁ'],
            correctOption: 1,
            difficultyTag: 'medium',
            points: 15,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
    ],
  },

  // 5. Mathematics - Fractions & Decimals
  {
    topic: {
      id: 'topic-math-fractions',
      subject: 'STEM - Mathematics',
      grade: 7,
      topic_name: 'Fractions, Decimals & Ratios',
      topic_name_odia: 'ଗଣିତ: ଭଗ୍ନାଂଶ, ଦଶମିକ ଏବଂ ଅନୁପାତ',
      order_index: 5,
      lesson_count: 2,
    },
    lessons: [
      {
        id: 'lesson-mastering-fractions',
        topicId: 'topic-math-fractions',
        grade: 7,
        subject: 'STEM - Mathematics',
        title: 'Mastering Fractions: Proper, Improper & Operations',
        titleOdia: 'ଭଗ୍ନାଂଶର ମୂଳଧାରଣା ଏବଂ ଗାଣିତିକ ପ୍ରକ୍ରିୟା',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'A fraction represents a part of a whole. Multiplication of fractions involves multiplying numerators together and denominators together.',
          summaryOdia: 'ଭଗ୍ନାଂଶ ଏକ ସମ୍ପୂର୍ଣ୍ଣ ବସ୍ତୁର ଅଂଶକୁ ବୁଝାଏ। ଭଗ୍ନାଂଶ ଗୁଣନ ପାଇଁ ଲବ ସହ ଲବ ଓ ହର ସହ ହର ଗୁଣାଯାଏ।',
          sections: [
            {
              title: 'Operations with Fractions',
              titleOdia: 'ଭଗ୍ନାଂଶର ଗୁଣନ ଓ ହରଣ',
              content: 'To divide by a fraction, multiply by its reciprocal: (a/b) ÷ (c/d) = (a/b) × (d/c).',
              contentOdia: 'ହରଣ କରିବା ପାଇଁ ହରକୁ ବ୍ୟୁତ୍କ୍ରମ (ଓଲଟାଇ) ଗୁଣନ କରାଯାଏ: (a/b) ÷ (c/d) = (a/b) × (d/c)।',
              keyPoints: ['Reciprocal of 3/5 is 5/3', 'Product of fractions = (Product of Numerators) / (Product of Denominators)'],
              keyPointsOdia: ['୩/୫ ର ବ୍ୟୁତ୍କ୍ରମ ହେଉଛି ୫/୩', 'ଲବ ଗୁଣନଫଳ / ହର ଗୁଣନଫଳ'],
            },
          ],
          realWorldOdisha: {
            title: 'Odisha Land Measurement: Guntha & Mana',
            titleOdia: 'ଓଡ଼ିଶାରେ ଜମି ମାପ: ଗୁଣ୍ଠ ଓ ମାଣ',
            context: 'In rural Odisha, farmland is divided into fractional units: 1 Mana = 25 Guntha.',
            contextOdia: 'ଓଡ଼ିଶାରେ ଚାଷଜମି ଭଗ୍ନାଂଶ ହିସାବରେ ବଣ୍ଟାଯାଏ: ୧ ମାଣ = ୨୫ ଗୁଣ୍ଠ।',
          },
          funFact: {
            en: 'The line separating numerator and denominator in a fraction is called the vinculum!',
            or: 'ଭଗ୍ନାଂଶରେ ଲବ ଓ ହର ମଧ୍ୟରେ ଥିବା ଗାରକୁ ଭିନକୁଲମ୍ (Vinculum) କୁହାଯାଏ!',
          },
        },
        mediaRefs: ['/media/fractions_mandi.png'],
        questions: [
          {
            id: 'q-frac-1',
            lessonId: 'lesson-mastering-fractions',
            questionText: 'What is the product of 2/3 and 5/7?',
            questionTextOdia: '୨/୩ ଏବଂ ୫/୭ ର ଗୁଣନଫଳ କେତେ?',
            options: ['10/21', '7/10', '10/14', '7/21'],
            optionsOdia: ['୧୦/୨୧', '୭/୧୦', '୧୦/୧୪', '୭/୨୧'],
            correctOption: 0,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-frac-2',
            lessonId: 'lesson-mastering-fractions',
            questionText: 'What is the reciprocal of the mixed fraction 2 1/3?',
            questionTextOdia: 'ମିଶ୍ର ଭଗ୍ନାଂଶ ୨ ୧/୩ ର ବ୍ୟୁତ୍କ୍ରମ (Reciprocal) କେତେ?',
            options: ['7/3', '3/7', '2/3', '3/2'],
            optionsOdia: ['୭/୩', '୩/୭', '୨/୩', '୩/୨'],
            correctOption: 1,
            difficultyTag: 'medium',
            points: 15,
          },
          {
            id: 'q-frac-3',
            lessonId: 'lesson-mastering-fractions',
            questionText: 'Evaluate: (3/4) ÷ (9/8)',
            questionTextOdia: 'ମାନ ନିର୍ଣ୍ଣୟ କର: (୩/୪) ÷ (୯/୮)',
            options: ['2/3', '3/2', '27/32', '1/2'],
            optionsOdia: ['୨/୩', '୩/୨', '୨୭/୩୨', '୧/୨'],
            correctOption: 0,
            difficultyTag: 'hard',
            points: 20,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
      {
        id: 'lesson-decimals-percentages',
        topicId: 'topic-math-fractions',
        grade: 7,
        subject: 'STEM - Mathematics',
        title: 'Decimals, Percentages and Real Applications',
        titleOdia: 'ଦଶମିକ, ଶତକଡ଼ା ଏବଂ ବ୍ୟବହାରିକ ପ୍ରୟୋଗ',
        contentVersion: 1,
        language: 'or',
        contentBody: {
          summary: 'Decimals and percentages are alternative representations of fractional parts, vital for financial literacy and measurements.',
          summaryOdia: 'ଦଶମିକ ଏବଂ ଶତକଡ଼ା ହେଉଛି ଭଗ୍ନାଂଶର ଅନ୍ୟ ରୂପ, ଯାହା ଦୈନନ୍ଦିନ ହିସାବରେ ବ୍ୟବହୃତ ହୁଏ।',
          sections: [
            {
              title: 'Converting Fractions to Decimals and Percentages',
              titleOdia: 'ଭଗ୍ନାଂଶରୁ ଦଶମିକ ଓ ଶତକଡ଼ା ରୂପାନ୍ତର',
              content: 'To convert fraction 3/4 to percentage: (3/4) × 100% = 75%. To decimal: 3 ÷ 4 = 0.75.',
              contentOdia: '୩/୪ କୁ ଶତକଡ଼ାରେ ପ୍ରକାଶ କଲେ: (୩/୪) × ୧୦୦% = ୭୫%। ଦଶମିକରେ: ୦.୭୫।',
              keyPoints: ['Percentage means per hundred', 'Multiply by 100 to convert to percentage'],
              keyPointsOdia: ['ଶତକଡ଼ା ଅର୍ଥ ପ୍ରତି ଶହେରେ', '୧୦୦ ଗୁଣି ଶତକଡ଼ା ବାହାର କରାଯାଏ'],
            },
          ],
          realWorldOdisha: {
            title: 'Odisha Farmers Market (Mandi) Calculations',
            titleOdia: 'ଓଡ଼ିଶା ଧାନ ମଣ୍ଡିରେ ଓଜନ ଓ ମୂଲ୍ୟ ହିସାବ',
            context: 'Paddy procurement at Mandis uses decimal metric tons and moisture percentage deductions.',
            contextOdia: 'ଧାନ ମଣ୍ଡିରେ କୁଇଣ୍ଟାଲ୍ ଓ ଦଶମିକ କିଲୋଗ୍ରାମ ହିସାବରେ ଧାନ କ୍ରୟ ହୁଏ।',
          },
          funFact: {
            en: 'The word "percent" comes from the Latin "per centum", meaning "by the hundred"!',
            or: 'ପରସେଣ୍ଟ୍ ଶବ୍ଦ ଲାଟିନ୍ ଭାଷା "ପର୍ ସେଣ୍ଟମ୍"ରୁ ଆସିଛି, ଯାହାର ଅର୍ଥ ପ୍ରତି ଶହେ!',
          },
        },
        mediaRefs: ['/media/decimals_percentage.png'],
        questions: [
          {
            id: 'q-dec-1',
            lessonId: 'lesson-decimals-percentages',
            questionText: 'Express 4/5 as a percentage:',
            questionTextOdia: '୪/୫ କୁ ଶତକଡ଼ାରେ ପ୍ରକାଶ କର:',
            options: ['40%', '60%', '80%', '85%'],
            optionsOdia: ['୪୦%', '୬୦%', '୮୦%', '୮୫%'],
            correctOption: 2,
            difficultyTag: 'easy',
            points: 10,
          },
          {
            id: 'q-dec-2',
            lessonId: 'lesson-decimals-percentages',
            questionText: 'What is 15% of 240 kg?',
            questionTextOdia: '୨୪୦ କିଲୋଗ୍ରାମର ୧୫% କେତେ?',
            options: ['30 kg', '36 kg', '42 kg', '45 kg'],
            optionsOdia: ['୩୦ କିଗ୍ରା', '୩୬ କିଗ୍ରା', '୪୨ କିଗ୍ରା', '୪୫ କିଗ୍ରା'],
            correctOption: 1,
            difficultyTag: 'medium',
            points: 15,
          },
        ],
        cachedAt: new Date().toISOString(),
      },
    ],
  },
];

// Helper to look up fallback lesson by ID, title, or topic
export function findSeedLesson(lookupIdOrTitle: string): CachedLesson | undefined {
  const clean = lookupIdOrTitle.toLowerCase().trim();
  for (const pack of CLIENT_SEED_PACKS) {
    for (const l of pack.lessons) {
      if (
        l.id === lookupIdOrTitle ||
        l.title.toLowerCase().trim() === clean ||
        (l.titleOdia && l.titleOdia.trim() === clean) ||
        clean.includes(l.title.toLowerCase().trim()) ||
        l.title.toLowerCase().trim().includes(clean)
      ) {
        return l;
      }
    }
  }
  return undefined;
}
